------------------------------------------------------------------------------
-- util_audit in-app help
--
-- One UTIL_AUDIT_DOC_ARTICLE row per topic, written in Markdown and rendered
-- with APEX_MARKDOWN.TO_HTML on the app's Documentation page (page 9).
-- PAGE_ID links an article to the screen it explains: Help in the top bar
-- opens page 9 with the current page number, and page 9 shows that article.
-- ADMIN_ONLY = Y hides an article from users who are not workspace
-- administrators or developers.
--
-- Installed by the Util Audit app's Supporting Objects. Safe to re-run: the
-- table is created only when missing. A missing article is added. An
-- article nobody has edited gets the new text; SEED_BODY keeps the text it
-- was shipped with, so an article edited in the app is never overwritten.
------------------------------------------------------------------------------

DECLARE
    PROCEDURE ddl(p_sql IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            -- ORA-00955: name already used, ORA-02260/02261: key already exists,
            -- ORA-01430: column already exists
            IF SQLCODE NOT IN (-955, -2260, -2261, -1430) THEN
                RAISE;
            END IF;
    END;
BEGIN
    ddl(q'[
create table UTIL_AUDIT_DOC_ARTICLE
(
    ID          NUMBER generated by default on null as identity
        constraint UTIL_AUDIT_DOC_ARTICLE_PK
            primary key,
    SLUG        VARCHAR2(100)  not null
        constraint UTIL_AUDIT_DOC_ARTICLE_SLUG_UK
            unique,
    TITLE       VARCHAR2(200)  not null,
    PAGE_ID     NUMBER,
    ADMIN_ONLY  VARCHAR2(1)    default 'N' not null
        constraint UTIL_AUDIT_DOC_ARTICLE_ADM_CK
            check (admin_only in ('Y', 'N')),
    SORT_ORDER  NUMBER         default 100 not null,
    BODY        CLOB,
    ACTIVE      VARCHAR2(1)    default 'Y' not null
        constraint UTIL_AUDIT_DOC_ARTICLE_ACT_CK
            check (active in ('Y', 'N')),
    CREATED     DATE           not null,
    CREATED_BY  VARCHAR2(255)  not null,
    UPDATED     DATE           not null,
    UPDATED_BY  VARCHAR2(255)  not null
)]');

    ddl(q'[create index UTIL_AUDIT_DOC_ARTICLE_PAGE_IX
    on UTIL_AUDIT_DOC_ARTICLE (PAGE_ID)]');

    -- The text the article was shipped with (added later)
    ddl(q'[alter table UTIL_AUDIT_DOC_ARTICLE add (SEED_BODY CLOB)]');
END;
/

create or replace trigger UTIL_AUDIT_DOC_ARTICLE_BIU
    before insert or update on UTIL_AUDIT_DOC_ARTICLE
    for each row
begin
    if inserting then
        :new.created    := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION', 'APP_USER'), user);
    end if;
    :new.updated    := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION', 'APP_USER'), user);
    :new.slug       := lower(regexp_replace(trim(:new.slug), '[^A-Za-z0-9-]+', '-'));
end;
/

-- Seed articles. Blank lines inside a PL/SQL block are safe in SQL*Plus,
-- SQLcl and APEX script runs, so the Markdown keeps its paragraphs.
DECLARE
    PROCEDURE seed(
        p_slug       IN VARCHAR2,
        p_title      IN VARCHAR2,
        p_page_id    IN NUMBER,
        p_admin_only IN VARCHAR2,
        p_sort_order IN NUMBER,
        p_body       IN CLOB
    ) IS
    BEGIN
        -- Unedited: the body is still the shipped text. Rows from before
        -- SEED_BODY existed count as unedited if never updated after insert.
        UPDATE util_audit_doc_article a
           SET body = p_body, seed_body = p_body
         WHERE a.slug = p_slug
           AND (DBMS_LOB.COMPARE(a.body, a.seed_body) = 0
                OR (a.seed_body IS NULL AND a.updated <= a.created + 2 / 86400)
                OR DBMS_LOB.COMPARE(a.body, p_body) = 0)
           -- only when something changes, so a re-run touches nothing
           AND (NVL(DBMS_LOB.COMPARE(a.body, p_body), 1) <> 0
                OR NVL(DBMS_LOB.COMPARE(a.seed_body, p_body), 1) <> 0);

        INSERT INTO util_audit_doc_article (slug, title, page_id, admin_only, sort_order, body, seed_body)
        SELECT p_slug, p_title, p_page_id, p_admin_only, p_sort_order, p_body, p_body
        FROM dual
        WHERE NOT EXISTS (SELECT 1 FROM util_audit_doc_article WHERE slug = p_slug);
    END;
BEGIN
    seed('getting-started', 'Getting started', NULL, 'N', 10, q'[
Util Audit records every change to the tables you choose: who changed which row, when, and what each column held before and after. It can also put a row back the way it was.

## Who can do what

| You are | You can |
| --- | --- |
| Workspace administrator or developer | Everything: start and stop auditing, restore rows, purge and archive history |
| Any other workspace user | Look at everything, change nothing |

## Finding your way

The menu at the top has **Home**, **Tables**, **Events**, **Row History**, **Errors**, **Maintenance**, **Archive**, **Query Generator** and **Documentation**. Maintenance and Archive only appear for administrators.

Press **Help** in the top bar on any screen to open the article for that screen.

The app follows your computer's light or dark setting. The **Theme** menu in the top bar switches between **Match system**, **Light** and **Dark**, and remembers your choice.

## Start in three steps

1. Open **Tables** and click a table name.
2. Press **Start Auditing**.
3. Change a row in that table. The change appears under **Events** straight away.
]');

    seed('home', 'Home', 1, 'N', 20, q'[
Home shows how much is being recorded.

## The four counts

1. **Audited tables**: tables with an audit trigger, whether paused or not.
2. **Events (24h)**: inserts, updates and deletes recorded in the last 24 hours.
3. **Events (7 days)**: the same for the last week.
4. **Errors (7 days)**: changes the triggers could not record. Anything above 0 is worth a look under **Errors**.

## Events per day

One bar per day for the last 14 days, split into inserts, updates and deletes.

## Recent events

The last 10 changes. Click the time to open the event.
]');

    seed('tables', 'Tables', 2, 'N', 30, q'[
Tables lists every table in the schema and whether it is audited. Click a table name to open it.

## Status

| Status | Meaning |
| --- | --- |
| Auditing | Changes are being recorded |
| Paused | The trigger is in place but records nothing |
| Not audited | No audit trigger on this table |
| Trigger invalid | The trigger does not compile. Open the table and press **Re-create Trigger** |
| Trigger disabled | Someone disabled the trigger in the database |

## Other columns

- **Ignored Columns**: bookkeeping columns whose changes are not listed.
- **Excluded Columns**: secrets that are never recorded at all.
- **Child Tables**: tables that point at this one with a foreign key. **Unaudited Child Tables** counts the ones without a trigger. Restoring a deleted row cannot bring back rows from those.
- **Events** and **Last Event**: how much has been recorded, and when last.

A table needs a primary key before it can be audited.
]');

    seed('auditing-a-table', 'Auditing a table', 3, 'N', 35, q'[
Open **Tables** and click a table name. The panel on the right shows the table's status and what you can do with it. Only administrators see the buttons.

## Buttons

| Button | What it does |
| --- | --- |
| **Start Auditing** | Creates the audit trigger. Recording starts at once |
| **Pause** | Stops recording but keeps the trigger |
| **Resume** | Starts recording again after a pause |
| **Re-create Trigger** | Rebuilds the trigger. Do this after adding or dropping columns |
| **Stop Auditing** | Removes the trigger. The history already recorded is kept |

## Ignored columns

Move the columns you do not want recorded to the right, then press **Save Ignored Columns**. The trigger is rebuilt straight away, and the list is kept every time the trigger is rebuilt.

A change that only touches ignored columns records nothing. These are always ignored: CREATED, CREATED_ON, CREATED_BY, UPDATED, UPDATED_ON, UPDATED_BY, MODIFIED, MODIFIED_ON, MODIFIED_BY.

Ignored columns are still kept in the copy of the whole row that each event stores, so a restored row gets them back.

## Excluded columns

For secrets, such as password hashes and reset tokens. An excluded column is never written to the audit trail: not as a change, and not in the copy of the whole row. Key columns cannot be excluded.

A restored row gets an empty value or the column default for excluded columns. If such a column is required and has no default, a deleted row cannot be restored, and Restore says so.

Turn on **Also remove them from history already recorded** to delete these columns from everything this table has recorded so far. This cannot be undone, and archive files made earlier keep them.

## Child tables

Lists every table that points at this one, how it reacts when a row here is deleted (**On Delete**), and whether it is audited.

When you restore a deleted row, Util Audit also brings back its child rows, but only from audited child tables. Audit the child tables too if you want restores to be complete.

## Trigger code

Shows the exact trigger the app creates for this table. Nothing runs when you open it.
]');

    seed('events', 'Events', 4, 'N', 40, q'[
Events lists every recorded change, newest first.

## Finding a change

- Type in **Search** to match any word in the list.
- Tick a **Table**, **Type** (INSERT, UPDATE or DELETE) or **User** to narrow the list. The numbers next to each value show how many events match.
- Enter dates under **When** and press **Go** to limit the time range.

## Columns

**Key** is the row's primary key. A key made of several columns is shown as `{"ORDER_ID":"100","LINE_NO":"1"}`. **Changed Columns** lists the columns that changed. An insert or delete lists every column.

## Opening a change

Click the time to see the full event and, for administrators, to restore the row. Click **History** to see every change to that row.
]');

    seed('event-and-restore', 'An event, and restoring a row', 5, 'N', 50, q'[
The Event panel shows one recorded change.

## What it shows

- **Event**: when, which table and row, what kind of change, and who made it. The user is the APEX user for changes made in an APEX app, otherwise the database user.
- **Context**: where the change came from. For an APEX app: the app, page and session numbers and the user's IP address. For other tools: the program name (**Module**), the computer (**Host**) and the operating-system user.
- **Column Changes**: each column's value before and after.

## Restoring a row

Restore puts the row back the way it was just before this event.

- For a **delete**, the row is inserted again.
- For an **update**, the columns go back to their old values.
- An **insert** cannot be restored.

1. Leave **Include child rows** on to also bring back rows in audited child tables that were deleted, or had their link cleared, in the same transaction.
2. Press **Preview Restore**. The restore runs, the **Result** box lists every row it would touch, and then everything is rolled back. Nothing changes.
3. If the result looks right, press **Restore**.

If the row changed again after this event, Restore stops and says so. Turn on **Overwrite later changes** to restore anyway. Those later changes are then lost.

If any step fails, nothing is changed. The reason appears in **Result**.

The restore is recorded like any other change. Its events show `util_audit.restore_row` as the **Action** in their context.

## What a restore cannot bring back

- Columns of unsupported types, such as BLOB. A re-inserted row gets an empty value or the column default for those.
- Events copied from util_audit v1. They have no copy of the whole row.
- Rows in child tables that are not audited. The Result says which tables these are.
- A row whose primary key is GENERATED ALWAYS AS IDENTITY, after a delete.
]');

    seed('row-history', 'Row History', 6, 'N', 60, q'[
Row History shows every recorded change to one row.

1. Choose the **Table**.
2. Choose the row's **Key**. The list shows every key that has events.

The **Timeline** lists the changes, newest first. Click one to open the event. **All Column Changes** lists each column's old and new value, change by change. Long values are cut at 200 characters here; open the event to see them in full.

Opening a change from **Events** with **History** fills in the table and key for you.

If a change altered the primary key, the history before and after it sits under two different keys.
]');

    seed('errors', 'Errors', 7, 'N', 70, q'[
When a trigger cannot record a change, the change itself still goes through. The failure is recorded here instead, so nothing is lost without a trace.

Each row shows when it happened, the table, the kind of change, the row's key, the user, and the error with the exact line it came from (**Backtrace**).

## What to do

- A single error: check the message. It usually names the cause, for example a value too large for a column.
- Many errors on one table after a change to that table: open the table under **Tables** and press **Re-create Trigger**.

Old errors can be deleted under **Maintenance**.
]');

    seed('maintenance', 'Maintenance', 8, 'Y', 80, q'[
Maintenance is for administrators.

## Purge Audit History

Deletes events, and their column changes, recorded before the date you choose. Choose a table to purge only that table. Deleted history cannot be restored, and rows cannot be restored from it.

To remove old history but keep a copy you can load back, use **Archive** instead.

## Purge Errors

Deletes logged errors recorded before the date you choose.

## Re-create All Triggers

Rebuilds every audit trigger from the current code. Do this after upgrading Util Audit, or after adding or dropping columns on several audited tables. The **Result** box lists each table and any that failed.
]');

    seed('how-auditing-works', 'How auditing works', NULL, 'N', 90, q'[
Each audited table has a trigger that runs after every insert, update and delete, once per row.

## What is recorded

- One **event** per changed row: when, who, the kind of change, the row's key, and the whole row before and after.
- One **column change** per changed column, with the old and new value. For an insert or a delete, every column that has a value.

An update that changes nothing, or only ignored columns, records nothing.

## Supported column types

NUMBER, FLOAT, BINARY_FLOAT, BINARY_DOUBLE, VARCHAR2, CHAR, NVARCHAR2, NCHAR, DATE, TIMESTAMP (with or without time zone), INTERVAL, CLOB and RAW (stored as hex). Other types, such as BLOB, are skipped.

Numbers and dates are always written the same way, whatever the user's language settings: `1234.5` and `2026-02-03T00:00:00`.

## Keys

A table needs a primary key. A key of one column is stored as its value, for example `42`. A key of several columns is stored as `{"ORDER_ID":"100","LINE_NO":"1"}`.

## Transactions

Audit records are part of the same transaction as the change. If the change is rolled back, so is its record.

## Speed

Every audited change does extra work. Audit the tables that matter, and avoid staging tables, bulk loads and high-volume logging tables.
]');

    seed('installing-and-upgrading', 'Installing and upgrading', NULL, 'Y', 100, q'[
## Installing

1. In App Builder, import the Util Audit app into the workspace.
2. Answer **Yes** to **Install Supporting Objects**. This creates the Util Audit tables, views and packages, and these help articles, in the workspace's schema.

## Upgrading

Import the new version over the old one and install its Supporting Objects again. Your audit history, settings and edited help articles are kept. Then open **Maintenance** and press **Re-create All Triggers** so every table uses the new trigger code.

## Schemas that have util_audit v1

If the schema already runs the older util_audit v1 (a UTIL_AUDIT_RECORDS table with a PK_VALUE column), installing stops with an error and changes nothing. Migrate the schema first with `migrate_v1.sql` from the util_audit repository, as described in its `docs/migrating-from-v1.md`, then install the app. The v1 history is kept, and the app shows it once it is copied.

## Removing

Delete the app in App Builder and choose to deinstall its Supporting Objects. This removes the triggers, packages, views, tables and the archive job, **including all audit history**. Export anything you need first. Archive files already in S3 stay there.
]');

    seed('query-generator', 'Query Generator', 11, 'N', 105, q'[
The Query Generator builds an **Audit History** region for a page in another app: the changes recorded for the row that page shows.

## Building a region

1. Choose the **Table** your page shows or edits.
2. Enter the **Page number in your app**. The key items are named after it, for example `P10_EMP_ID`. If your items have other names, enter them in **Key page items** instead, one per key column, in key column order.
3. Choose what to **Show**:
    - **One row per changed column**: each column's old and new value.
    - **One row per change**: one line per insert, update or delete, listing the columns that changed.
4. Optional: pick **Only these columns**, and choose **Include child tables** to also show changes to rows that point at this one, for example an employee's tasks.
5. Press **Generate**.

## Three ways to add it to your app

- **Audit History plugin**, the easiest. Add the plugin to your app once, then add a region of type Audit History and set Table and Key Items. APEXlang apps can paste the generated block.
- **SQL for App Builder**: create a Classic Report (or any report) region and paste the SQL. It reads `util_audit_query.history`, so it keeps working as util_audit improves. Turn on **Plain SQL** for a query that calls no package.
- **APEXlang Region**: a complete Classic Report region to paste into a page's `.apx` file.

**Preview** shows what the region will display for a row that already has changes.

## From SQL

The same history is available anywhere:

`select * from table(util_audit_query.history('EMP', :P10_EMP_ID))`

Give one key value per key column (`p_key1`, `p_key2`, ...). Optional: `p_style => 'EVENTS'`, `p_columns`, `p_child_tables`, `p_max_rows`.

## If your app uses another schema

Enter the util_audit schema in **util_audit schema**, and grant your app's schema EXECUTE on UTIL_AUDIT_QUERY. For plain SQL, grant SELECT on V_UTIL_AUDIT_ROW_HISTORY, V_UTIL_AUDIT_EVENTS and UTIL_AUDIT_RECORDS instead.

## Keys

Keys are matched as text, so a key item must hold the value exactly as stored, for example `100`, not `100.0`.
]');

    seed('archive', 'Archive', 12, 'Y', 85, q'[
Moves old audit history out of the audit tables into files, preferably in Amazon S3, and brings it back when needed.

## How it works

Each file holds one table's events for one calendar month, as gzipped JSON lines. Every archive goes through these steps:

1. **Archive**: the file is built.
2. **Store**: the file is sent to its storage, then read back and compared, so a damaged upload is never counted as stored.
3. **Purge** (only if you turn it on): the month's events are deleted from the audit tables, after checking that they still match the file.
4. **Restore** (when needed): the month's events are loaded back. Loading twice does no harm.

## Storage and retention

| Storage | Where the files go |
|---|---|
| Database | Kept in the archive table itself |
| Amazon S3 via AWS4_S3_PKG | Your bucket, through the S3 package this schema already uses for documents |
| Object storage via DBMS_CLOUD | Needs a DBMS_CLOUD credential and a base URI |
| Custom procedure | Your own procedure and function, for any other system |

**Months to keep** says how many recent months stay in the audit tables; older complete months are archived. **Delete archived months** is off at first, so the first runs only make copies. Turn it on once you have restored one archive and checked it.

## Schedule

**Schedule** creates a database job that archives every night (it needs the CREATE JOB privilege). **Run Now** does the same work straight away. The last run's result shows here; a failed step says why in the file list.

## Archive files

One row per file, with its status: Created, Stored, Purged, Restored or Failed. You can store a file again after a failure, purge it, restore it, or download it.

A restored month is archived again by the next scheduled run. To keep it in the tables for a while, stop the schedule or raise **Months to keep**.
]');

    seed('documentation', 'Documentation', 9, 'N', 110, q'[
Documentation lists every help topic. Click a topic to read it, or type a word in **Search** to find topics that mention it.

**Help** in the top bar opens the article for the screen you are on.

## Editing articles

Administrators see **New Article** and **Edit**.

- **Linked screen**: the screen whose Help opens this article. Leave it empty for a general topic.
- **Administrators only**: hides the article from users who are not administrators.
- **Order**: where the article sits in the topic list. Lower numbers come first.
- **Active**: turn off to hide an article without deleting it.
- **Body**: the article, in Markdown. `## ` starts a heading, `**bold**`, `- ` starts a list item, and `| a | b |` rows make a table.

Upgrading Util Audit adds new articles and brings unedited ones up to date. An article you edited here is left as you wrote it.
]');

    COMMIT;
END;
/
