------------------------------------------------------------------------------
-- GENERATED by tools/bundle_v1_migration.py from the util_audit repository.
-- Do not edit; change the sources and re-run the tool.
--
-- The same as migrate_v1_history.sql. Safe to run again.
------------------------------------------------------------------------------
set define off verify off feedback off serveroutput on size unlimited
whenever sqlerror exit failure rollback

------------------------------------------------------------------------------
-- util_audit: copy the util_audit v1 history into the new tables
--
-- Run after migrate_v1.sql, from the repository folder, as the schema owner:
--
--   @migrate_v1_history.sql
--
-- Copies UTIL_AUDIT_RECORDS_V1 into UTIL_AUDIT_TXN (one event per v1
-- TRANSACTION_ID) and UTIL_AUDIT_RECORDS, one month of one table at a time,
-- committing after each. The apps can stay in use. If it stops, run it
-- again: it skips what it already copied.
--
-- The copied events have no row snapshots, so they show in the history
-- views, the app and util_audit_query, but util_audit.restore_row cannot
-- restore them. The v1 USERENV text is kept in AUDIT_CONTEXT as v1_userenv.
--
-- When everything is copied, V_UTIL_AUDIT_RECORDS_V1 is rebuilt to read the
-- new tables only. UTIL_AUDIT_RECORDS_V1 is then no longer needed; drop it
-- yourself once you have checked the copy:
--   drop table util_audit_records_v1 purge;
------------------------------------------------------------------------------

set define off verify off feedback off serveroutput on size unlimited
whenever sqlerror exit failure rollback

DECLARE
    l_events  NUMBER;
    l_rows    NUMBER;
    l_total_e NUMBER := 0;
    l_total_r NUMBER := 0;
    l_skipped NUMBER;
    l_cur     SYS_REFCURSOR;
    l_table   VARCHAR2(255);
    l_month   DATE;

    -- The event key: the v1 transaction id, or one per row when v1 had none
    c_key CONSTANT VARCHAR2(200) := q'[coalesce(to_char(v.transaction_id), 'V1-' || v.util_audit_record_id)]';
BEGIN
    -- Month by month, so the new ids come out in time order
    OPEN l_cur FOR q'[
        select table_name, trunc(audit_date, 'MM')
          from util_audit_records_v1
         where table_name is not null
         group by trunc(audit_date, 'MM'), table_name
         order by 2 nulls first, 1]';
    LOOP
        FETCH l_cur INTO l_table, l_month;
        EXIT WHEN l_cur%NOTFOUND;

        -- One event (header) per v1 transaction id
        EXECUTE IMMEDIATE q'[
            insert into util_audit_txn
                (transaction_id, table_name, pk_value_vc, transaction_type, username, audit_context, audit_ts)
            select k, :t, min(to_char(pk_value)), min(transaction_type), substr(min(username), 1, 255),
                   json_object('source' value 'util_audit v1', 'v1_userenv' value min(userenv) absent on null),
                   cast(min(audit_date) as timestamp)
              from (select v.*, ]' || c_key || q'[ k
                      from util_audit_records_v1 v
                     where v.table_name = :t
                       and (trunc(v.audit_date, 'MM') = :m or (:m is null and v.audit_date is null))
                       and v.transaction_type in ('INSERT', 'UPDATE', 'DELETE')) v
             where not exists (select 1 from util_audit_txn x where x.transaction_id = v.k)
             group by k]'
            USING l_table, l_table, l_month, l_month;
        l_events := SQL%ROWCOUNT;

        -- Its changed columns, unless an earlier run copied them already
        EXECUTE IMMEDIATE q'[
            insert into util_audit_records
                (transaction_id, table_name, pk_value_vc, column_name, data_type, transaction_type,
                 username, old_value, new_value, old_clob, new_clob, audit_ts)
            select v.k, v.table_name, to_char(v.pk_value), v.column_name, substr(v.data_type, 1, 128),
                   v.transaction_type, substr(v.username, 1, 255), v.old_value, v.new_value,
                   v.old_clob, v.new_clob, cast(v.audit_date as timestamp)
              from (select v.*, ]' || c_key || q'[ k
                      from util_audit_records_v1 v
                     where v.table_name = :t
                       and (trunc(v.audit_date, 'MM') = :m or (:m is null and v.audit_date is null))
                       and v.transaction_type in ('INSERT', 'UPDATE', 'DELETE')) v
             where exists (select 1 from util_audit_txn x where x.transaction_id = v.k)
               and not exists (select 1 from util_audit_records r where r.transaction_id = v.k)
             order by v.audit_date, v.util_audit_record_id]'
            USING l_table, l_month, l_month;
        l_rows := SQL%ROWCOUNT;
        COMMIT;

        l_total_e := l_total_e + l_events;
        l_total_r := l_total_r + l_rows;
        IF l_events > 0 OR l_rows > 0 THEN
            DBMS_OUTPUT.PUT_LINE(RPAD(l_table, 32) || NVL(TO_CHAR(l_month, 'YYYY-MM'), 'no date') ||
                                 ': ' || l_events || ' events, ' || l_rows || ' rows');
        END IF;
    END LOOP;
    CLOSE l_cur;

    DBMS_OUTPUT.PUT_LINE('Copied ' || l_total_e || ' events, ' || l_total_r || ' rows.');

    EXECUTE IMMEDIATE q'[
        select count(*) from util_audit_records_v1
         where table_name is null or transaction_type is null
            or transaction_type not in ('INSERT', 'UPDATE', 'DELETE')]'
        INTO l_skipped;
    IF l_skipped > 0 THEN
        DBMS_OUTPUT.PUT_LINE(l_skipped || ' v1 rows have no table name or transaction type and were not copied.');
    END IF;
END;
/

-- Rebuild the compatibility view: without the archive once all is copied
-- ===== migration/v1_compat_view.sql =====
------------------------------------------------------------------------------
-- V_UTIL_AUDIT_RECORDS_V1: all audit history in the util_audit v1 column
-- layout, for pages and code written against the v1 UTIL_AUDIT_RECORDS.
-- Called by migrate_v1.sql and migrate_v1_history.sql.
--
--   PK_VALUE     NUMBER when v1 stored numbers (text keys give NULL; use
--                PK_VALUE_VC for those), else text
--   USERENV      the v1 text for v1 events; the JSON context for new ones
--   AUDIT_DATE   AUDIT_TS as a DATE
--
-- While UTIL_AUDIT_RECORDS_V1 holds rows that migrate_v1_history.sql has
-- not copied yet, the view reads them from there.
------------------------------------------------------------------------------
DECLARE
    l_numeric BOOLEAN;
    l_archive NUMBER;
    l_left    NUMBER := 0;
    l_pk      VARCHAR2(200);
    l_sql     VARCHAR2(32767);
    l_type    VARCHAR2(128);
BEGIN
    SELECT COUNT(*) INTO l_archive FROM user_tables WHERE table_name = 'UTIL_AUDIT_RECORDS_V1';
    IF l_archive > 0 THEN
        SELECT data_type INTO l_type FROM user_tab_columns
         WHERE table_name = 'UTIL_AUDIT_RECORDS_V1' AND column_name = 'PK_VALUE';
        EXECUTE IMMEDIATE q'[
            select count(*) from util_audit_records_v1 v
             where rownum = 1
               and not exists (select 1 from util_audit_txn x
                                where x.transaction_id = coalesce(to_char(v.transaction_id), 'V1-' || v.util_audit_record_id))]'
            INTO l_left;
    ELSE
        -- Archive dropped: keep the key type the view had
        SELECT MAX(data_type) INTO l_type FROM user_tab_columns
         WHERE table_name = 'V_UTIL_AUDIT_RECORDS_V1' AND column_name = 'PK_VALUE';
    END IF;
    l_numeric := NVL(l_type, 'NUMBER') = 'NUMBER';

    IF l_numeric THEN
        -- The same expression as the index UTIL_AUDIT_RECORDS_V1PK_IX, so
        -- "pk_value = :P1_ID" is an index lookup
        l_pk := 'to_number(r.pk_value_vc default null on conversion error)';
        BEGIN
            EXECUTE IMMEDIATE 'create index util_audit_records_v1pk_ix on util_audit_records (table_name, ' ||
                              'to_number(pk_value_vc default null on conversion error))';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE NOT IN (-955, -1408) THEN
                    RAISE;
                END IF;
        END;
    ELSE
        l_pk := 'r.pk_value_vc';
    END IF;

    l_sql := q'[create or replace view v_util_audit_records_v1 as
select r.util_audit_record_id,
       r.transaction_id,
       r.table_name,
       ]' || l_pk || q'[ as pk_value,
       r.pk_value_vc,
       r.column_name,
       r.data_type,
       r.transaction_type,
       r.username,
       r.old_value,
       r.new_value,
       r.old_clob,
       r.new_clob,
       coalesce(json_value(t.audit_context, '$.v1_userenv' returning varchar2(4000)),
                dbms_lob.substr(t.audit_context, 4000, 1)) as userenv,
       cast(r.audit_ts as date) as audit_date
  from util_audit_records r
  left join util_audit_txn t
    on t.transaction_id = r.transaction_id]';

    IF l_left > 0 THEN
        l_sql := l_sql || q'[
union all
select v.util_audit_record_id,
       to_char(v.transaction_id),
       v.table_name,
       v.pk_value,
       to_char(v.pk_value),
       v.column_name,
       v.data_type,
       v.transaction_type,
       v.username,
       v.old_value,
       v.new_value,
       v.old_clob,
       v.new_clob,
       v.userenv,
       v.audit_date
  from util_audit_records_v1 v
 where not exists (select 1 from util_audit_txn x
                    where x.transaction_id = coalesce(to_char(v.transaction_id), 'V1-' || v.util_audit_record_id))]';
    END IF;

    EXECUTE IMMEDIATE l_sql;
    DBMS_OUTPUT.PUT_LINE('View V_UTIL_AUDIT_RECORDS_V1 ' ||
        CASE WHEN l_left > 0 THEN 'reads the new tables and the uncopied v1 archive.'
             ELSE 'reads the new tables only.' END);
END;
/


set feedback on
whenever sqlerror continue
