#!/usr/bin/env python3
"""Build single-file versions of the v1 migration for migration runners.

Some projects run each migration file on its own, with `set define off` and
no arguments (for example a scripts/migrate.sh that does `@file`). The
repository scripts use @@ includes and an EXECUTE argument, so they do not
work there. This writes self-contained files that do:

  migration/bundle/util_audit_v1_view_first.sql = migration/v1_view_before_migrating.sql
  migration/bundle/util_audit_v1_migrate.sql    = migrate_v1.sql EXECUTE
  migration/bundle/util_audit_v1_history.sql    = migrate_v1_history.sql

Copy them into the project's migrations folder under its own naming rules.
Re-run this after changing setup.sql or anything under migration/.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIG = ROOT / "migration"
OUT = MIG / "bundle"


def inline(text, base):
    """Replace @@file lines with the file's content, recursively."""
    def repl(m):
        path = (base / m.group(1).strip()).resolve()
        return f"-- ===== {path.relative_to(ROOT)} =====\n" + inline(path.read_text(), path.parent) + "\n"
    return re.sub(r"(?m)^@@(\S+)\s*$", repl, text)


def check(name, text):
    if re.search(r"(?m)^@", text):
        raise SystemExit(f"{name}: an @ include is left")
    if "&" in text:
        raise SystemExit(f"{name}: contains '&', which a runner with define on would treat as a substitution variable")


PRECHECK = """-- Stop unless this schema has util_audit v1, or a migration that did not finish
DECLARE
    l_v1  NUMBER;
    l_log NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_v1 FROM user_tables t
     WHERE t.table_name = 'UTIL_AUDIT_RECORDS'
       AND NOT EXISTS (SELECT 1 FROM user_tab_columns c
                        WHERE c.table_name = t.table_name AND c.column_name = 'PK_VALUE_VC');
    SELECT COUNT(*) INTO l_log FROM user_tables WHERE table_name = 'UTIL_AUDIT_V1_TRIGGERS';
    IF l_v1 = 0 AND l_log = 0 THEN
        RAISE_APPLICATION_ERROR(-20111, 'No util_audit v1 here (no UTIL_AUDIT_RECORDS with PK_VALUE), so nothing to migrate.');
    END IF;
END;
/
"""

HEADER = """------------------------------------------------------------------------------
-- GENERATED by tools/bundle_v1_migration.py from the util_audit repository.
-- Do not edit; change the sources and re-run the tool.
--
{what}
------------------------------------------------------------------------------
set define off verify off feedback off serveroutput on size unlimited
whenever sqlerror exit failure rollback

"""


def main():
    OUT.mkdir(exist_ok=True)

    migrate = HEADER.format(what=(
        "-- util_audit v1 -> current, in one file: the same as running\n"
        "-- \"@migrate_v1.sql EXECUTE\" from the repository. See the README section\n"
        "-- \"Where util_audit v1 already exists\". Safe to run again if it stops.")) + \
        PRECHECK + inline((MIG / "migrate_v1_execute.sql").read_text(), MIG)
    check("util_audit_v1_migrate.sql", migrate)
    (OUT / "util_audit_v1_migrate.sql").write_text(migrate)

    first = HEADER.format(what="-- The same as migration/v1_view_before_migrating.sql. Safe to run again.") + \
        (MIG / "v1_view_before_migrating.sql").read_text()
    check("util_audit_v1_view_first.sql", first)
    (OUT / "util_audit_v1_view_first.sql").write_text(first)

    history = (ROOT / "migrate_v1_history.sql").read_text()
    history = HEADER.format(what="-- The same as migrate_v1_history.sql. Safe to run again.") + \
        inline(history, ROOT)
    check("util_audit_v1_history.sql", history)
    (OUT / "util_audit_v1_history.sql").write_text(history)

    for f in sorted(OUT.iterdir()):
        print(f"Wrote {f.relative_to(ROOT)} ({f.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
